# vim:set ts=8 sts=8 sw=8 noet:
DNAME := nettle-3.4
FNAME := nettle-3.4.tar.gz
DLINK := https://ftp.gnu.org/gnu/nettle/nettle-3.4.tar.gz


CFLAGS := "-I${OUTPUT}/include/"
LDFLAGS := "-L${OUTPUT}/lib/"

export CFLAGS LDFLAGS



all : ${FNAME} ${DNAME} config
	make -C ${DNAME}
	make -C ${DNAME} install


${FNAME} :
	wget ${DLINK}


${DNAME} :
	tar xvfx ${FNAME}


config :
	cd ${DNAME} && \
		CFLAGS=${CFLAGS} LDFLAGS=${LDFLAGS} ./configure --host=${HOSTOPT} --prefix=${OUTPUT}
